#!/usr/bin/env bash
# install.sh  –  install nvda_tracker as a systemd service
# ─────────────────────────────────────────────────────────
# Must be run as root (or via sudo).
# Usage:
#   sudo bash install.sh
# ─────────────────────────────────────────────────────────
set -euo pipefail

# ── configurable ─────────────────────────────────────────────────────────────
INSTALL_DIR="/opt/nvda-tracker"
VENV_DIR="${INSTALL_DIR}/.venv"
SCRIPT_SRC="nvda_tracker.py"          # expected next to this install.sh
UNIT_NAME="nvda-tracker"
UNIT_FILE="/etc/systemd/system/${UNIT_NAME}.service"
LOG_TAG="[install]"

# ── colours ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}${LOG_TAG}${NC} $*"; }
warn()  { echo -e "${YELLOW}${LOG_TAG} WARN:${NC} $*"; }
die()   { echo -e "${RED}${LOG_TAG} ERROR:${NC} $*" >&2; exit 1; }

# ── sanity checks ─────────────────────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Please run as root: sudo bash install.sh"
command -v python3 >/dev/null 2>&1 || die "python3 not found – install it first"
command -v systemctl >/dev/null 2>&1 || die "systemctl not found – systemd required"

PYTHON=$(command -v python3)
PY_VER=$("$PYTHON" -c 'import sys; print(sys.version_info[:2] >= (3,9))')
[[ "$PY_VER" == "True" ]] || die "Python 3.9+ required (for zoneinfo). Found: $($PYTHON --version)"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "${SCRIPT_DIR}/${SCRIPT_SRC}" ]] || \
    die "${SCRIPT_SRC} not found next to install.sh (expected in ${SCRIPT_DIR})"

# ── 1. create install directory & copy script ─────────────────────────────────
info "Step 1/3 – Installing files to ${INSTALL_DIR} …"
install -d -o root -g root -m 755 "${INSTALL_DIR}"
install -o root -g root -m 644 "${SCRIPT_DIR}/${SCRIPT_SRC}" "${INSTALL_DIR}/${SCRIPT_SRC}"
info "  script installed."

# ── 2. create venv & install dependencies ────────────────────────────────────
info "Step 2/3 – Creating virtual environment at ${VENV_DIR} …"
"$PYTHON" -m venv "${VENV_DIR}"
"${VENV_DIR}/bin/pip" install --quiet --upgrade pip
"${VENV_DIR}/bin/pip" install --quiet yfinance
# world-readable so the DynamicUser allocated by systemd can execute it
chmod -R a+rX "${VENV_DIR}"
info "  venv ready."

# ── 3. write systemd unit & enable ────────────────────────────────────────────
info "Step 3/3 – Writing systemd unit ${UNIT_FILE} …"
cat > "${UNIT_FILE}" << EOF
# Auto-generated by install.sh – re-run install.sh to update

[Unit]
Description=NVDA intraday stock price tracker
After=network-online.target
Wants=network-online.target

[Service]
Type=simple

# systemd allocates a transient user/group and creates the state directory.
DynamicUser=yes
StateDirectory=nvda-tracker

ExecStart=${VENV_DIR}/bin/python3 ${INSTALL_DIR}/${SCRIPT_SRC}

Restart=on-failure
RestartSec=15s
TimeoutStopSec=30

StandardOutput=journal
StandardError=journal
SyslogIdentifier=${UNIT_NAME}

Environment=PYTHONUNBUFFERED=1
Environment=NVDA_STATE_FILE=/var/lib/nvda-tracker/nvda_today

NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
chmod 644 "${UNIT_FILE}"
info "  unit file written."

systemctl daemon-reload
systemctl enable "${UNIT_NAME}"
systemctl restart "${UNIT_NAME}"

sleep 2

STATUS=$(systemctl is-active "${UNIT_NAME}" 2>&1 || true)
if [[ "$STATUS" == "active" ]]; then
    info "  Service is ${GREEN}active${NC} ✓"
else
    warn "  Service status: ${STATUS}"
    warn "  Check logs: journalctl -u ${UNIT_NAME} -n 30 --no-pager"
fi

# ── done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Installation complete.${NC}"
echo ""
echo "  Useful commands:"
echo "    journalctl -u ${UNIT_NAME} -f            # follow live logs"
echo "    journalctl -u ${UNIT_NAME} --since today  # today's full log"
echo "    systemctl status  ${UNIT_NAME}            # service status"
echo "    systemctl stop    ${UNIT_NAME}            # stop"
echo "    systemctl start   ${UNIT_NAME}            # start"
echo "    systemctl disable ${UNIT_NAME}            # remove from autostart"
echo ""
echo "  State file:  /var/lib/nvda-tracker/nvda_today"
echo "  Script:      ${INSTALL_DIR}/${SCRIPT_SRC}"
echo "  Venv:        ${VENV_DIR}"
echo ""
